spring:
  datasource:
    url: jdbc:mysql://waffle-prod.cz6os4e28f0d.ap-northeast-2.rds.amazonaws.com:3306/waffle_order?user=admin
    username: admin
    password: Park12378!  
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Workbench?? ?? ???? ????? 'none'?? ??
    show-sql: true # SQL ??? ??? ?? (????)
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ??



